config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  resources :friends
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  before_action :correct_user, only: [:edit,:update,:destory]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id]) 
    redirect_to friends_path, notice: "Not Authorized To Edit this Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    @about_me = "My name is Michael!"
    @answer = "the answer to everything is #{42}." 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter @ here" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>
  <br>
  <div>
    <%= form.submit "Add This Friend", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">

<table class="table table-dark table-striped table-bordered table-hover table-responsive">
  <thead>
    <tr>
      
      <th scope="col">Full Name:</th>
      <th scope="col">Email:</th>
      <th scope="col">Phone:</th>
      <th scope="col">Twitter:</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to friend.first_name+' '+friend.last_name, friend, class:"btn btn-success"%></td>
      <td><%= friend.email %></td>
      <td><%= friend.phone %></td>
      <td><%= friend.twitter %></td>
      
    </tr>
  </tbody>
</table>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-dark" %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-success" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

<div  id="friends">
  <% @friends.each do |friend| %>
  <% if friend.user == current_user%>
    <%= render friend %> 
  <%end%>
  <% end %>
</div>

<%= link_to "New friend", new_friend_path, class: "btn btn-primary" %>

<% else %>

<h1>Hello World</h1>
This is my first rails Webpage.

<% end %>

app/views/friends/new.html.erb
<div>
</div>

<div class="card text-center">
  <div class="card-header">
    <h4>Add New friend</h4>
  </div>
  <div class="card-body">
    <p class="card-text"><%= render "form", friend: @friend %></p>
  </div>
  <div class="card-footer text-muted">
    <%= link_to "Back to friends", friends_path, class:"btn btn-success" %>
  </div>
</div>
  <br>

app/views/friends/show.html.erb
<div class="jumbotron jumbotron-fluid" >
  <h1 class="display-4"><%=@friend.first_name%> <%=@friend.last_name%></h1>
  <p class="lead"><%=@friend.email%> | <%=@friend.phone%> | <%=@friend.twitter%></p>
  <hr class="my-4">

  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-dark"  %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-success" %>

  
</div>
<br>
<div>
  <%= button_to "Delete This Record", @friend, method: :delete,  class:"btn btn-danger btn-sm" %>
</div>
<br>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%=link_to 'Friend App', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
        	<%=link_to "About Us", home_about_path, class: "nav-link"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%=link_to "New Friends", new_friend_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
          <%=button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-danger ml-3"%>
          </li>
          <li class="nav-item">
          <%=link_to "Edit Profile", edit_user_registration_path, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%=link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%=link_to "Sign In", new_user_session_path, class: "nav-link"%>
          </li>
        <% end %>
        
        </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us...</h1>

<p>
	
	<%= @about_me%>

	<%= @answer%>

</p>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first rails Webpage.

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <%end%>
      <br/>
      <%= yield %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

  </body>
</html>